// <auto-generated/>
#pragma warning disable CS0618
using ECommerce.Clients.Orders.Orders.Client.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ECommerce.Clients.Orders.Orders.Client
{
    /// <summary>
    /// Builds and executes requests for operations under \orders\client
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ECommerce.Clients.Orders.orders.client.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Orders.Client.Item.WithClientItemRequestBuilder"/></returns>
        public global::ECommerce.Clients.Orders.Orders.Client.Item.WithClientItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("clientId", position);
                return new global::ECommerce.Clients.Orders.Orders.Client.Item.WithClientItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ECommerce.Clients.Orders.orders.client.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Orders.Client.Item.WithClientItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ECommerce.Clients.Orders.Orders.Client.Item.WithClientItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("clientId", position);
                return new global::ECommerce.Clients.Orders.Orders.Client.Item.WithClientItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Orders.Client.ClientRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orders/client", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Orders.Client.ClientRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orders/client", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
