// <auto-generated/>
#pragma warning disable CS0618
using ECommerce.Clients.Users.Admins.External;
using ECommerce.Clients.Users.Admins.Item;
using ECommerce.Clients.Users.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ECommerce.Clients.Users.Admins
{
    /// <summary>
    /// Builds and executes requests for operations under \admins
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdminsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The external property</summary>
        public global::ECommerce.Clients.Users.Admins.External.ExternalRequestBuilder External
        {
            get => new global::ECommerce.Clients.Users.Admins.External.ExternalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ECommerce.Clients.Users.admins.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Users.Admins.Item.WithAdminItemRequestBuilder"/></returns>
        public global::ECommerce.Clients.Users.Admins.Item.WithAdminItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("adminId", position);
                return new global::ECommerce.Clients.Users.Admins.Item.WithAdminItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ECommerce.Clients.Users.admins.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Users.Admins.Item.WithAdminItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ECommerce.Clients.Users.Admins.Item.WithAdminItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("adminId", position);
                return new global::ECommerce.Clients.Users.Admins.Item.WithAdminItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Users.Admins.AdminsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admins", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Users.Admins.AdminsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admins", rawUrl)
        {
        }
        /// <summary>
        /// Creates a new administrator workspace account profile.
        /// </summary>
        /// <returns>A <see cref="global::ECommerce.Clients.Users.Models.AdminResponseDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerce.Clients.Users.Models.ApiProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ECommerce.Clients.Users.Models.ConflictProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::ECommerce.Clients.Users.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ECommerce.Clients.Users.Models.AdminResponseDto?> PostAsync(global::ECommerce.Clients.Users.Models.CreateAdminRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ECommerce.Clients.Users.Models.AdminResponseDto> PostAsync(global::ECommerce.Clients.Users.Models.CreateAdminRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ECommerce.Clients.Users.Models.ApiProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::ECommerce.Clients.Users.Models.ConflictProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ECommerce.Clients.Users.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ECommerce.Clients.Users.Models.AdminResponseDto>(requestInfo, global::ECommerce.Clients.Users.Models.AdminResponseDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new administrator workspace account profile.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ECommerce.Clients.Users.Models.CreateAdminRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ECommerce.Clients.Users.Models.CreateAdminRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ECommerce.Clients.Users.Admins.AdminsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ECommerce.Clients.Users.Admins.AdminsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ECommerce.Clients.Users.Admins.AdminsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AdminsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
