// <auto-generated/>
#pragma warning disable CS0618
using ECommerce.Clients.Orders.Invoices.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ECommerce.Clients.Orders.Invoices
{
    /// <summary>
    /// Builds and executes requests for operations under \invoices
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvoicesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ECommerce.Clients.Orders.invoices.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder"/></returns>
        public global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("client%2Did", position);
                return new global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ECommerce.Clients.Orders.invoices.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("client%2Did", position);
                return new global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Invoices.InvoicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvoicesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/invoices", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Invoices.InvoicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvoicesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/invoices", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
