// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerce.Clients.Orders.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderLineResponseDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The brand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Brand { get; set; }
#nullable restore
#else
        public string Brand { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The productVersionId property</summary>
        public Guid? ProductVersionId { get; set; }
        /// <summary>The quantity property</summary>
        public int? Quantity { get; set; }
        /// <summary>The totalAmount property</summary>
        public double? TotalAmount { get; set; }
        /// <summary>The totalCurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalCurrency { get; set; }
#nullable restore
#else
        public string TotalCurrency { get; set; }
#endif
        /// <summary>The unitPriceAmount property</summary>
        public double? UnitPriceAmount { get; set; }
        /// <summary>The unitPriceCurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitPriceCurrency { get; set; }
#nullable restore
#else
        public string UnitPriceCurrency { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Models.OrderLineResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerce.Clients.Orders.Models.OrderLineResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerce.Clients.Orders.Models.OrderLineResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brand", n => { Brand = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "productVersionId", n => { ProductVersionId = n.GetGuidValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "totalAmount", n => { TotalAmount = n.GetDoubleValue(); } },
                { "totalCurrency", n => { TotalCurrency = n.GetStringValue(); } },
                { "unitPriceAmount", n => { UnitPriceAmount = n.GetDoubleValue(); } },
                { "unitPriceCurrency", n => { UnitPriceCurrency = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("brand", Brand);
            writer.WriteStringValue("name", Name);
            writer.WriteGuidValue("productVersionId", ProductVersionId);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteDoubleValue("totalAmount", TotalAmount);
            writer.WriteStringValue("totalCurrency", TotalCurrency);
            writer.WriteDoubleValue("unitPriceAmount", UnitPriceAmount);
            writer.WriteStringValue("unitPriceCurrency", UnitPriceCurrency);
        }
    }
}
#pragma warning restore CS0618
