// <auto-generated/>
#pragma warning disable CS0618
using ECommerce.Clients.Users.Admins;
using ECommerce.Clients.Users.Customers;
using ECommerce.Clients.Users.Documentation;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ECommerce.Clients.Users
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersApiClient : BaseRequestBuilder
    {
        /// <summary>The admins property</summary>
        public global::ECommerce.Clients.Users.Admins.AdminsRequestBuilder Admins
        {
            get => new global::ECommerce.Clients.Users.Admins.AdminsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customers property</summary>
        public global::ECommerce.Clients.Users.Customers.CustomersRequestBuilder Customers
        {
            get => new global::ECommerce.Clients.Users.Customers.CustomersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The documentation property</summary>
        public global::ECommerce.Clients.Users.Documentation.DocumentationRequestBuilder Documentation
        {
            get => new global::ECommerce.Clients.Users.Documentation.DocumentationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Users.UsersApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
