// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerce.Clients.Users.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerResponseDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The companies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ECommerce.Clients.Users.Models.CompanyDataResponseDto>? Companies { get; set; }
#nullable restore
#else
        public List<global::ECommerce.Clients.Users.Models.CompanyDataResponseDto> Companies { get; set; }
#endif
        /// <summary>The externalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The individual property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerce.Clients.Users.Models.IndividualDataResponseDto? Individual { get; set; }
#nullable restore
#else
        public global::ECommerce.Clients.Users.Models.IndividualDataResponseDto Individual { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerce.Clients.Users.Models.CustomerResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerce.Clients.Users.Models.CustomerResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerce.Clients.Users.Models.CustomerResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "companies", n => { Companies = n.GetCollectionOfObjectValues<global::ECommerce.Clients.Users.Models.CompanyDataResponseDto>(global::ECommerce.Clients.Users.Models.CompanyDataResponseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "individual", n => { Individual = n.GetObjectValue<global::ECommerce.Clients.Users.Models.IndividualDataResponseDto>(global::ECommerce.Clients.Users.Models.IndividualDataResponseDto.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ECommerce.Clients.Users.Models.CompanyDataResponseDto>("companies", Companies);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<global::ECommerce.Clients.Users.Models.IndividualDataResponseDto>("individual", Individual);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
