// <auto-generated/>
#pragma warning disable CS0618
using ECommerce.Clients.Orders.Invoices.Item.Item;
using ECommerce.Clients.Orders.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ECommerce.Clients.Orders.Invoices.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \invoices\{client-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ECommerce.Clients.Orders.invoices.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Invoices.Item.Item.WithOrderItemRequestBuilder"/></returns>
        public global::ECommerce.Clients.Orders.Invoices.Item.Item.WithOrderItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("orderId", position);
                return new global::ECommerce.Clients.Orders.Invoices.Item.Item.WithOrderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ECommerce.Clients.Orders.invoices.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Invoices.Item.Item.WithOrderItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ECommerce.Clients.Orders.Invoices.Item.Item.WithOrderItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("orderId", position);
                return new global::ECommerce.Clients.Orders.Invoices.Item.Item.WithOrderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/invoices/{client%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/invoices/{client%2Did}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the invoice when the Id exists; 404 otherwise.
        /// </summary>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Models.InvoiceResponseDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerce.Clients.Orders.Models.ApiProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ECommerce.Clients.Orders.Models.NotFoundProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::ECommerce.Clients.Orders.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ECommerce.Clients.Orders.Models.InvoiceResponseDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ECommerce.Clients.Orders.Models.InvoiceResponseDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ECommerce.Clients.Orders.Models.ApiProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::ECommerce.Clients.Orders.Models.NotFoundProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ECommerce.Clients.Orders.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ECommerce.Clients.Orders.Models.InvoiceResponseDto>(requestInfo, global::ECommerce.Clients.Orders.Models.InvoiceResponseDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the invoice when the Id exists; 404 otherwise.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ECommerce.Clients.Orders.Invoices.Item.ClientItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClientItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
