// <auto-generated/>
#pragma warning disable CS0618
using ECommerce.Clients.Orders.ClientDataVersions;
using ECommerce.Clients.Orders.Documentation;
using ECommerce.Clients.Orders.Invoices;
using ECommerce.Clients.Orders.Orders;
using ECommerce.Clients.Orders.ShoppingCarts;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ECommerce.Clients.Orders
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrdersApiClient : BaseRequestBuilder
    {
        /// <summary>The clientDataVersions property</summary>
        public global::ECommerce.Clients.Orders.ClientDataVersions.ClientDataVersionsRequestBuilder ClientDataVersions
        {
            get => new global::ECommerce.Clients.Orders.ClientDataVersions.ClientDataVersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The documentation property</summary>
        public global::ECommerce.Clients.Orders.Documentation.DocumentationRequestBuilder Documentation
        {
            get => new global::ECommerce.Clients.Orders.Documentation.DocumentationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invoices property</summary>
        public global::ECommerce.Clients.Orders.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::ECommerce.Clients.Orders.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::ECommerce.Clients.Orders.Orders.OrdersRequestBuilder Orders
        {
            get => new global::ECommerce.Clients.Orders.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shoppingCarts property</summary>
        public global::ECommerce.Clients.Orders.ShoppingCarts.ShoppingCartsRequestBuilder ShoppingCarts
        {
            get => new global::ECommerce.Clients.Orders.ShoppingCarts.ShoppingCartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.OrdersApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
