// <auto-generated/>
#pragma warning disable CS0618
using ECommerce.Clients.Orders.Documentation.Flows;
using ECommerce.Clients.Orders.Documentation.Validations;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ECommerce.Clients.Orders.Documentation
{
    /// <summary>
    /// Builds and executes requests for operations under \documentation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DocumentationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The flows property</summary>
        public global::ECommerce.Clients.Orders.Documentation.Flows.FlowsRequestBuilder Flows
        {
            get => new global::ECommerce.Clients.Orders.Documentation.Flows.FlowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validations property</summary>
        public global::ECommerce.Clients.Orders.Documentation.Validations.ValidationsRequestBuilder Validations
        {
            get => new global::ECommerce.Clients.Orders.Documentation.Validations.ValidationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Documentation.DocumentationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/documentation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerce.Clients.Orders.Documentation.DocumentationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/documentation", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
